const validAccounts = [
    { username: "Heri heryadi", kta: "0001", password: "heri123" },
    { username: "Muhammad Rizkiansyah", kta: "0002", password: "rizki123" },
    { username: "Habibi ganteng bang", kta: "0003", password: "habibi234" },
    { username: "ARJUNA PAMUNGKAS", kta: "0004", password: "arjuna23" },
    { username: "Aldino Arya Saputera", kta: "0005", password: "aldino321" },
    { username: "Muhammad Khaidir", kta: "0006", password: "khaidir245" },
    { username: "Andyka Rizky Sobar", kta: "0007", password: "andyka789" },
    { username: "Parawangsa Alifianto", kta: "0008", password: "parawangsa456" },
    { username: "Rachmat Aprianto", kta: "0009", password: "rachmat567" },
    { username: "Imam Arif Badawi", kta: "0010", password: "imam910" },
    { username: "Fihad Fauzan", kta: "0011", password: "fihad112" },
    { username: "M Septian Maulana", kta: "0012", password: "septian123" },
    { username: "ALDI HADIANSYAH", kta: "0013", password: "aldi321" },
    { username: "Muhammad Daffa", kta: "0014", password: "daffa234" },
    { username: "Muhammad iqbal addin", kta: "0015", password: "iqbal456" },
    { username: "SALMAN ALPARISI", kta: "0016", password: "salman456" },
    { username: "Delin Irgi Saputra", kta: "0017", password: "delin567" },
    { username: "Mochammad Putrama wijaya", kta: "0018", password: "putrama678" },
    { username: "Puspita aprilia", kta: "0019", password: "puspita789" },
    { username: "Febri Fitrianto", kta: "0020", password: "febri123" },
    { username: "Eki Apriandi solichan", kta: "0021", password: "eki321" },
    { username: "Faras Kharisma", kta: "0022", password: "faras456" },
    { username: "MUHAMAD IRCHAM PANGESTU", kta: "0023", password: "ircham789" },
    { username: "Ilyas arya saputra", kta: "0024", password: "ilyas123" },
    { username: "Muhammad rizky irmawansyah", kta: "0025", password: "rizky321" },
    { username: "Achmad suseno", kta: "0026", password: "achmad234" },
    { username: "Andhika Faris", kta: "0027", password: "andhika345" },
    { username: "Allyffia Zahra", kta: "0028", password: "allyffia456" },
    { username: "M Rizky H", kta: "0029", password: "rizky789" },
    { username: "Haidar Yahya", kta: "0030", password: "haidar123" },
    { username: "Moses Aditya", kta: "0031", password: "moses234" },
    { username: "Pahri Perdinan Kamil", kta: "0032", password: "pahri345" },
    { username: "Muhammad Rafli Alvaro", kta: "0033", password: "rafli456" },
    { username: "Farhanaprian", kta: "0034", password: "farhan123" },
    { username: "Rifki Fadhilah", kta: "0035", password: "rifki234" },
    { username: "Muhammad aufan Fachrian", kta: "0036", password: "aufan567" },
    { username: "Ahmadhabibi", kta: "0037", password: "ahmad789" },
    { username: "Alfaro Azmi triamantiyo", kta: "0038", password: "alfaro123" },
    { username: "Muhammad. Tubagus Rizki", kta: "0039", password: "rizki456" },
    { username: "muhammad giffary", kta: "0040", password: "giffary789" },
    { username: "Prasetyo", kta: "0041", password: "prasetyo321" },
    { username: "Muhammad Rizky Kemal", kta: "0042", password: "kemal123" },
    { username: "ADAM RAMY ESFANDIAR", kta: "0043", password: "adam123" },
    { username: "Muhammad siraz", kta: "0044", password: "siraz234" },
    { username: "William Din Yunus", kta: "0045", password: "william567" },
    { username: "Muhamad rizky", kta: "0046", password: "rizky890" },
    { username: "imanuel yos Pradana", kta: "0047", password: "imanuel321" },
    { username: "M.Naufal Rafiansyah Abyantoro", kta: "0048", password: "naufal789" },
    { username: "LULU ALIFIA VANISA", kta: "0049", password: "lulu456" },
    { username: "Zaenal Mustofa", kta: "0050", password: "zaenal123" },
    { username: "HASAN AL AHWARI", kta: "0051", password: "hasan234" },
    { username: "M Reza", kta: "0052", password: "reza789" },
    { username: "Ferdin Ramadhan Achmad", kta: "0053", password: "ferdin123" },
    { username: "Mifta Arif rahmat", kta: "0054", password: "mifta567" },
    { username: "Hilmy Alim Syarif", kta: "0055", password: "hilmy234" },
    { username: "Ricky Setiawan", kta: "0056", password: "ricky789" },
    { username: "RUBBEN PRADITA", kta: "0057", password: "rubben321" },
    { username: "Muhamad Iqbal Amrullah", kta: "0058", password: "iqbal456" },
    { username: "Satria rahman dwiansyah", kta: "0059", password: "satria123" },
    { username: "Dhea zahra", kta: "0060", password: "dhea789" },
    { username: "Suci Harianti", kta: "0061", password: "suci234" },
    { username: "Agung Dwi Prastyo", kta: "0062", password: "agung345" },
    { username: "Muhammad Rizieq Arsyad", kta: "0063", password: "rizieq567" },
    { username: "Muhammad Wahyudin", kta: "0064", password: "wahyudin123" },
    { username: "Agil Pramono", kta: "0065", password: "agil678" },
    { username: "Farel", kta: "0066", password: "farel123" },
    { username: "Nadia Putri Salsabila", kta: "0067", password: "nadia345" },
    { username: "Asyazid Prasetyo Alfandhi", kta: "0068", password: "asyazid567" },
    { username: "Ferdyansyah", kta: "0069", password: "ferdyansyah123" },
    { username: "Vhiky jhaky", kta: "0070", password: "vhiky789" },
    { username: "Taufik Hidayat", kta: "0071", password: "taufik123" },
    { username: "NATANIA ARIFIN", kta: "0072", password: "natania456" },
    { username: "david eduardom", kta: "0073", password: "david567" },
    { username: "Muhammad Syahril Alamsyah", kta: "0074", password: "syahril123" },
    { username: "Yudi kuswara", kta: "0075", password: "yudi234" },
    { username: "Cahyo imam maulana", kta: "0076", password: "cahyo567" },
    { username: "Firjatullah Apta I.D", kta: "0077", password: "firjatulla123" },
    { username: "Raditya Fajar Laksono", kta: "0078", password: "raditya234" },
    { username: "LUTHFI AZZAM DHIYAULHAQ", kta: "0079", password: "luthfi567" },
    { username: "Ontong Saputra", kta: "0080", password: "ontong789" },
    { username: "Adhitya Prawira Yudha", kta: "0081", password: "adhitya234" },
    { username: "Yazid wizdan", kta: "0082", password: "yazid345" },
    { username: "hendi kusuma jaya", kta: "0083", password: "hendi567" },
    { username: "Heri Susanto", kta: "0084", password: "heri890" },
    { username: "Muhammad Reza zulmi", kta: "0085", password: "reza234" },
    { username: "Ridho Ariotama Adi Danuarta", kta: "0086", password: "ridho789" },
    { username: "Ghali Ghazian Ramadhan", kta: "0087", password: "ghali123" },
    { username: "Reegi Muhammad Sudirman", kta: "0088", password: "reegi456" },
    { username: "Mohammad Walid Ridho", kta: "0089", password: "walid890" },
    { username: "Muhammad rafka Ihza Pahlevi", kta: "0090", password: "rafka123" },
    { username: "Muhammad Rafka Yusla", kta: "0091", password: "yusla234" },
    { username: "M.APRILIYANTO", kta: "0092", password: "april123" },
    { username: "Hamdani Yanto", kta: "0093", password: "hamdani567" },
    { username: "Sammy Arsyi Yusuf", kta: "0094", password: "sammy789" },
    { username: "Luthfi Zulfiansyah", kta: "0095", password: "luthfi890" },
    { username: "Muhamad Ridwan", kta: "0096", password: "ridwan123" },
    { username: "Rafa putra", kta: "0097", password: "rafa234" },
    { username: "Fathir Ahmad Maulana", kta: "0098", password: "fat14" },
    { username: "Muhammad Fiqih", kta: "0099", password: "fiqih456" },
    { username: "Agnes Kartika", kta: "0100", password: "agnes789" },
    { username: "Satrya try ardhyanto", kta: "0101", password: "satrya123" },
    { username: "Saipul ajis", kta: "0102", password: "saipul234" },
    { username: "Rafli Rachmad Ramadhan", kta: "0103", password: "rafli567" },
    { username: "MUHAMMAD ADLY FAYRUZ SEHAN", kta: "0104", password: "adly789" },
    { username: "SEPTIAN TRI", kta: "0105", password: "septian890" },
    { username: "Febry Primas Firmansyah", kta: "0106", password: "febry123" },
    { username: "Fadhillah putra R", kta: "0107", password: "fadhillah456" },
    { username: "Raikhan luluh saputra", kta: "0108", password: "raikhan567" },
    { username: "Muhammad Yusuf", kta: "0109", password: "yusuf678" },
    { username: "Amir Aksar", kta: "0110", password: "amir789" },
    { username: "DIWA ANUGRAH RAMADHAN", kta: "0111", password: "diwa123" },
    { username: "M.Raehan Al Farizy", kta: "0112", password: "raehan234" },
    { username: "Muhammad hafiz", kta: "0113", password: "hafiz567" },
    { username: "Sepson Mora Tambunan", kta: "0114", password: "sepson678" },
    { username: "Ferdinand Ibrahim", kta: "0115", password: "ferdin123" },
    { username: "Yusril Ihza Mahendra", kta: "0116", password: "yusril456" },
    { username: "Muhammad Adyuta Rizki Fadhillah", kta: "0117", password: "adyuta789" },
    { username: "Adhitya Prawira Yudha", kta: "0118", password: "adhitya345" },
    { username: "Akhdan Yusuf Aditya", kta: "0119", password: "akhdan567" },
    { username: "Fajar Pratama", kta: "0120", password: "fajar678" },
    { username: "Maulana Rifai", kta: "0121", password: "rifai789" },
    { username: "Arief Rangga Saputra", kta: "0122", password: "arief123" },
    { username: "Yehezkielnathan", kta: "0123", password: "yehez123" },
    { username: "Busthomi", kta: "0124", password: "busthomi456" },
    { username: "FIAN DWI SANTOSO", kta: "0125", password: "fian789" },
    { username: "Muhammad Raivaldo Alif Putra", kta: "0126", password: "raivaldo123" },
    { username: "Ibnu Zaki", kta: "0127", password: "ibnu456" },
    { username: "Kenzhie emeraldy wibowo", kta: "0128", password: "kenzhie567" },
    { username: "Dzakwan Aditya Fairuz", kta: "0129", password: "dzakwan678" },
    { username: "Fadhilah langgeng pangestu", kta: "0130", password: "fadhilah789" },
    { username: "Resky Alhafiz", kta: "0131", password: "resky123" },
    { username: "Moch Fikri", kta: "0132", password: "fikri234" },
    { username: "Sulthan shadiq andra tusyahbi", kta: "0133", password: "sulthan567" },
    { username: "Ajeng Siti Lucyani", kta: "0134", password: "ajeng789" },
    { username: "Rasyiqha Syafa Rabbanny", kta: "0135", password: "cika123" },
    { username: "Jastro Bayu Prasetyo", kta: "0136", password: "jastro234" },
    { username: "Fauzan Ismail", kta: "0137", password: "fauzan345" },
    { username: "Mohamad Raihan Hafizd", kta: "0138", password: "raihan456" },
    { username: "Ahmad fauzan", kta: "0139", password: "ahmad567" },
    { username: "Rizky Achmad Imam Bayhaki", kta: "0140", password: "rizky789" },
    { username: "OKTA ARDIANSYAH", kta: "0141", password: "okta123" },
    { username: "Muhammad iksan rifa’i", kta: "0142", password: "iksan456" },
    { username: "Okky Firmansyah", kta: "0143", password: "okky789" },
    { username: "Almas Tito Rifa'i", kta: "0144", password: "tito123" },
    { username: "Vincent Vasca Vasca Valentino Risel", kta: "0145", password: "vincent456" },
    { username: "Nawaf Mumtaz Al Ghifari", kta: "0146", password: "nawaf567" },
    { username: "Muhammad Arseja", kta: "0147", password: "arseja123" },
    { username: "Daniel Edric Hotasi Siburian", kta: "0148", password: "daniel456" },
    { username: "satriyo bagus triadmojo", kta: "0149", password: "satriyo567" },
    { username: "reiza rilis tgl 1, mayan buat ngantek csot/masinis", kta: "0150", password: "reiza789" },
    { username: "Nanda risqi ramadan", kta: "0151", password: "nanda123" },
    { username: "Agung Eka Pratama", kta: "0152", password: "agung234" },
    { username: "Shofwan Adli hanan", kta: "0153", password: "shofwan345" },
    { username: "Dzulhijjah", kta: "0154", password: "dzulhijjah456" },
    { username: "Rizky farid arbain", kta: "0155", password: "rizky567" },
    { username: "Adam Fadilah Permana", kta: "0156", password: "adam789" },
    { username: "danureza setiaBudi", kta: "0157", password: "danureza123" },
    { username: "Muhammad Naufal Atsilul Ikhsan", kta: "0158", password: "naufal234" },
    { username: "Muhammad Rasya birda tama", kta: "0159", password: "rasya345" },
    { username: "David Sukmawan", kta: "0160", password: "david456" },
    { username: "JOHANNAF ACHSAN ARD", kta: "0161", password: "johannaf567" },
    { username: "Zya afif aulia", kta: "0162", password: "zya678" },
    { username: "Fauzi albadri", kta: "0163", password: "fauzi789" },
    { username: "Andhika firzatullah", kta: "0164", password: "andhika123" },
    { username: "Shalman Nur Aliv", kta: "0165", password: "shalman234" },
    { username: "ADRIANSYAH RAKA DWI PUTRA KURMAWAN", kta: "0166", password: "adriansyah345" },
    { username: "Shofwan adli hanan", kta: "0167", password: "shofwan456" },
    { username: "Muhammad Gerry aldiano", kta: "0168", password: "gerry567" },
    { username: "Harfi Ramadhan Salim", kta: "0169", password: "harfi789" },
    { username: "Alvin Hermansyah", kta: "0170", password: "alvin123" },
    { username: "Reiza Hendriansyah", kta: "0171", password: "reiza234" },
    { username: "Muhammad Hafiizh Abdurraafi", kta: "0172", password: "hafiizh345" },
    { username: "Muhammad Fazlur Rahman", kta: "0173", password: "fazlur456" },
    { username: "Muhamad Fauzan", kta: "0174", password: "fauzan567" },
    { username: "Alif Alfarizi Rosada", kta: "0175", password: "alif678" },
    { username: "Muhamad Fajri Ridho", kta: "0177", password: "fajri789" },
    { username: "salsabila", kta: "0176", password: "salsabila123" },
    { username: "Muhammad Ilham Ramadhan", kta: "0178", password: "ilham234" },
    { username: "Rizal Kristiawan", kta: "0179", password: "rizal345" },
    { username: "Dimitri Setya", kta: "0180", password: "dimitri456" },
    { username: "FIRMANSYAH", kta: "0181", password: "firmansyah567" },
    { username: "Muhammad nadhif hisyam", kta: "0182", password: "nadhif678" },
    { username: "Dzakir rafiqi afkar", kta: "0183", password: "dzakir789" },
    { username: "Ferdi Ardiansyah", kta: "0184", password: "ferdi890" },
    { username: "Cahyo imam maulana", kta: "0185", password: "cahyo123" },
    { username: "Rayhan Maulana", kta: "0186", password: "rayhan234" },
    { username: "Riffat", kta: "0187", password: "riffat345" },
    { username: "Aldiko Araya", kta: "0188", password: "aldiko456" },
    { username: "rio satriawan", kta: "0189", password: "rio567" },
    { username: "IBNU MALIK AL KAILANI", kta: "0190", password: "ibnu678" },
    { username: "Alif Ryan Hakim", kta: "0191", password: "alif789" },
    { username: "Chandra Zaldiyansyah", kta: "0192", password: "chandra890" },
    { username: "adella puspa susanah", kta: "0193", password: "adella123" },
    { username: "Eliezer Clarence Nadek", kta: "0194", password: "eliezer234" },
    { username: "Risky eka putra", kta: "0195", password: "risky345" },
    { username: "Muhaimin Iskandar Khadafi", kta: "0196", password: "muhaimin456" },
    { username: "Falah khalifano putra wibowo", kta: "0197", password: "falah567" },
    { username: "Dendra Hafis", kta: "0198", password: "dendra678" },
    { username: "Reo Rizky Widodo", kta: "0199", password: "reo789" },
    { username: "MIKHAEL Febriyanto laya", kta: "0200", password: "mikhael123" },
    { username: "Monica Gabriella Simanjuntak", kta: "0201", password: "monica234" },
    { username: "Prayoga hibatullah", kta: "0202", password: "prayoga345" },
    { username: "Rachmat Aprianto", kta: "0203", password: "rachmat456" },
    { username: "Adam MaliQiSaputra", kta: "0204", password: "adam567" },
    { username: "Abi Dzar Ismail", kta: "0205", password: "abi678" },
    { username: "Muhammad Sabiq Firdaus", kta: "0206", password: "sabiq789" },
    { username: "Miqdad Ifzal Rao", kta: "0207", password: "miqdad123" },
    { username: "ADRIANSYAH RAKA DWI PUTRA KUSMAWAN", kta: "0208", password: "adriansyah234" },
    { username: "Muhammad Fahri", kta: "0209", password: "fahri345" },
    { username: "Muhammad Nur Mauladin", kta: "0210", password: "mauladin456" },
    { username: "Adnan Taqwa Junior", kta: "0211", password: "adnan567" },
    { username: "Irfan Maulana Wirawijaya", kta: "0212", password: "irfan678" },
    { username: "M.Alfazely Wibisono", kta: "0213", password: "alfazely789" },
    { username: "Rizky aal Fathir", kta: "0214", password: "aal123" },
    { username: "irfan Ardiansyah", kta: "0215", password: "irfan234" },
    { username: "Ramadhan Arya Prayoga", kta: "0216", password: "yoga321" },
    { username: "Ananda Febriyanti", kta: "0261", password: "nanda11125" },
    { username: "Vibie Reyhan Aban", kta: "0262", password: "vibie987" },
{ username: "Muhammad Ahnaf Ghifary", kta: "0260", password: "ahnaf432" },
{ username: "Raditya Hadi Sumantri", kta: "0230", password: "raditya105" },
{ username: "Fahry ihza putra", kta: "0253", password: "fahry826" },
{ username: "Bilal Bani Adam", kta: "0245", password: "bilal739" },
{ username: "Idzhar fatekhatul Ramdan", kta: "0228", password: "idzhar384" },
{ username: "Ardi Firmansyah", kta: "0249", password: "ardi901" },
{ username: "Fikri Akbar Sujana", kta: "0240", password: "fikri277" },
{ username: "Kelvin Nelson", kta: "0244", password: "kelvin660" },
{ username: "Daffa Ardiansyah", kta: "0227", password: "daffa194" },
{ username: "Abimulia Saleh", kta: "0263", password: "abimulia508" },
{ username: "Akmal Wibisana", kta: "0217", password: "akmal712" },
{ username: "Muhammad Akram Indriawan", kta: "0252", password: "akram885" },
{ username: "Raisya anandita", kta: "0270", password: "raisya303" },
{ username: "Kenneth Alexander", kta: "0242", password: "kenneth147" },
{ username: "Alvito Bima Nurfaqih", kta: "0254", password: "alvito936" },
{ username: "Andika Firzatullah", kta: "0268", password: "andika644" },
{ username: "Genevie Nofell", kta: "0257", password: "genevie128" },
{ username: "Akbar Nurhidayanto", kta: "0234", password: "akbar571" },
{ username: "Raihan Alzena", kta: "0249", password: "raihan869" },
{ username: "Indah hurun aeni", kta: "0243", password: "indah453" },
{ username: "Fahrezy Rizky Haditya", kta: "0247", password: "fahrezy220" },
{ username: "Giriyama romero", kta: "0269", password: "giriyama374" },
{ username: "Muhammad Sidqi Rabbani", kta: "0272", password: "sidqi998" },
{ username: "Alvi Anugerah", kta: "0220", password: "alvi117" },
{ username: "Riyandi Aziz", kta: "0221", password: "riyandi659" }
];