const validAccounts = [
    { username: "Heri heryadi", kta: "0001", password: "heri123" },
    { username: "Arjuna Pamungkas", kta: "0004", password: "arjuna23" },
    { username: "Muhammad Khaidir", kta: "0006", password: "khaidir245" },
    { username: "M Septian Maulana", kta: "0012", password: "septian123" },
    { username: "Aldi Hadiansyah", kta: "0013", password: "aldi321" },
    { username: "Salman Alparisi", kta: "0016", password: "salman456" },
    { username: "Eki Apriandi solichan", kta: "0021", password: "eki321" },
    { username: "Muhammad Rizky Hidayat", kta: "0029", password: "rizky789" },
    { username: "Haidar Yahya", kta: "0030", password: "haidar123" },
    { username: "Farhanaprian", kta: "0034", password: "farhan123" },
    { username: "Alfaro Azmi triamantiyo", kta: "0038", password: "alfaro123" },
    { username: "Muhammad Rizky Kemal", kta: "0042", password: "kemal123" },
    { username: "Adam Ramy Esfandiar", kta: "0043", password: "adam123" },
    { username: "Muhammad siraz", kta: "0044", password: "siraz234" },
    { username: "HASAN AL AHWARI", kta: "0051", password: "hasan234" },
    { username: "Rubben Pradita", kta: "0057", password: "rubben321" },
    { username: "Agung Dwi Prastyo", kta: "0062", password: "agung345" },
    { username: "Muhammad Rizieq Arsyad", kta: "0063", password: "rizieq567" },
    { username: "Agil Pramono", kta: "0065", password: "agil678" },
    { username: "Asyazid Prasetyo Alfandhi", kta: "0068", password: "asyazid567" },
    { username: "Ferdyansyah", kta: "0069", password: "ferdyansyah123" },
    { username: "Vhiky jhaky", kta: "0070", password: "vhiky789" },
    { username: "Yudi kuswara", kta: "0075", password: "yudi234" },
    { username: "Ridho Ariotama Adi Danuarta", kta: "0086", password: "ridho789" },
    { username: "Mohammad Walid Ridho", kta: "0089", password: "walid890" },
    { username: "Muhammad rafka Ihza Pahlevi", kta: "0090", password: "rafka123" },
    { username: "M.Apriliyanto", kta: "0092", password: "april123" },
    { username: "Muhamad Ridwan", kta: "0096", password: "ridwan123" },
    { username: "Rafa putra", kta: "0097", password: "rafa234" },
    { username: "Fathir Ahmad Maulana", kta: "0098", password: "fat14" },
    { username: "Satrya try ardhyanto", kta: "0101", password: "satrya123" },
    { username: "Raikhan luluh saputra", kta: "0108", password: "raikhan567" },
    { username: "Amir Aksar", kta: "0110", password: "amir789" },
    { username: "Muhammad Adyuta Rizki Fadhillah", kta: "0117", password: "adyuta789" },
    { username: "Akhdan Yusuf Aditya", kta: "0119", password: "akhdan567" },
    { username: "Yeskil Nathaniel", kta: "0123", password: "yeskil123" },
    { username: "Ibnu Zaki", kta: "0127", password: "ibnu456" },
    { username: "Kenzhie emeraldy wibowo", kta: "0128", password: "kenzhie567" },
    { username: "Moch Fikri", kta: "0132", password: "fikri234" },
    { username: "Sulthan shadiq andra tusyahbi", kta: "0133", password: "sulthan567" },
    { username: "Rasyiqha Syafa Rabbanny", kta: "0135", password: "cika123" },
    { username: "Ahmad fauzan", kta: "0139", password: "ahmad567" },
    { username: "Almas Tito Rifa'i", kta: "0144", password: "tito123" },
    { username: "Nanda risqi ramadan", kta: "0151", password: "nanda123" },
    { username: "Danureza Setiabudi", kta: "0157", password: "danureza123" },
    { username: "Johannaf Achsan Ard", kta: "0161", password: "johannaf567" },
    { username: "Zya afif aulia", kta: "0162", password: "zya678" },
    { username: "Fauzi albadri", kta: "0163", password: "fauzi789" },
    { username: "Muhammad Hafiizh Abdurraafi", kta: "0172", password: "hafiizh345" },
    { username: "Muhamad Fauzan", kta: "0174", password: "fauzan567" },
    { username: "Muhamad Fajri Ridho", kta: "0177", password: "fajri789" },
    { username: "Dimitri Setya", kta: "0180", password: "dimitri456" },
    { username: "Dzakir Rafiqi Afkar", kta: "0183", password: "dzakir321" },
    { username: "Aldiko Araya", kta: "0188", password: "aldiko456" },
    { username: "Eliezer Clarence Nadek", kta: "0194", password: "eliezer234" },
    { username: "Adam Maliqi Saputra", kta: "0204", password: "adam567" },
    { username: "Abi Dzar Ismail", kta: "0205", password: "abi678" },
    { username: "Muhammad Sabiq Firdaus", kta: "0206", password: "sabiq789" },
    { username: "Miqdad Ifzal Rao", kta: "0207", password: "miqdad123" },
    { username: "Adnan Taqwa Junior", kta: "0211", password: "adnan567" },
    { username: "Irfan Maulana Wirawijaya", kta: "0212", password: "irfan678" },
    { username: "M.Alfazely Wibisono", kta: "0213", password: "alfazely789" },
    { username: "Rizky aal Fathir", kta: "0214", password: "aal123" },
    { username: "Ramadhan Arya Prayoga", kta: "0216", password: "yoga321" },
    { username: "Ananda Febriyanti", kta: "0261", password: "nanda11125" },
    { username: "Vibie Reyhan Aban", kta: "0262", password: "vibie987" },
{ username: "Muhammad Ahnaf Ghifary", kta: "0260", password: "ahnaf432" },
{ username: "Raditya Hadi Sumantri", kta: "0230", password: "raditya105" },
{ username: "Fahry ihza putra", kta: "0253", password: "fahry826" },
{ username: "Bilal Bani Adam", kta: "0245", password: "bilal739" },
{ username: "Idzhar fatekhatul Ramdan", kta: "0228", password: "idzhar384" },
{ username: "Ardi Firmansyah", kta: "0249", password: "ardi901" },
{ username: "Fikri Akbar Sujana", kta: "0240", password: "fikri277" },
{ username: "Kelvin Nelson", kta: "0244", password: "kelvin660" },
{ username: "Daffa Ardiansyah", kta: "0227", password: "daffa194" },
{ username: "Abimulia Saleh", kta: "0263", password: "abimulia508" },
{ username: "Akmal Wibisana", kta: "0217", password: "akmal712" },
{ username: "Muhammad Akram Indriawan", kta: "0252", password: "akram885" },
{ username: "Raisya anandita", kta: "0270", password: "raisya303" },
{ username: "Kenneth Alexander", kta: "0242", password: "kenneth147" },
{ username: "Alvito Bima Nurfaqih", kta: "0254", password: "alvito936" },
{ username: "Andhika Firzatullah", kta: "0268", password: "andika644" },
{ username: "Genevie Nofell", kta: "0257", password: "genevie128" },
{ username: "Akbar Nurhidayanto", kta: "0234", password: "akbar571" },
{ username: "Raihan Alzena", kta: "0248", password: "raihan869" },
{ username: "Indah hurun aeni", kta: "0243", password: "indah453" },
{ username: "Fahrezy Rizky Haditya", kta: "0247", password: "fahrezy220" },
{ username: "Giriyama romero", kta: "0269", password: "giriyama374" },
{ username: "Muhammad Sidqi Rabbani", kta: "0272", password: "sidqi998" },
{ username: "Alvi Anugerah", kta: "0220", password: "alvi117" },
{ username: "Muhammad Hery", kta: "0219", password: "hery117" },
{ username: "Riyandi Aziz", kta: "0221", password: "riyandi659" }
];